# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaapp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(655, 159)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.edtValidarCPF = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.edtValidarCPF.setFont(font)
        self.edtValidarCPF.setObjectName("edtValidarCPF")
        self.gridLayout.addWidget(self.edtValidarCPF, 0, 1, 1, 1)
        self.btnValidarCpf = QtWidgets.QPushButton(self.centralwidget)
        self.btnValidarCpf.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnValidarCpf.setFont(font)
        self.btnValidarCpf.setObjectName("btnValidarCpf")
        self.gridLayout.addWidget(self.btnValidarCpf, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.btnGerarCPF = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnGerarCPF.setFont(font)
        self.btnGerarCPF.setObjectName("btnGerarCPF")
        self.gridLayout.addWidget(self.btnGerarCPF, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.edtRetorno = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.edtRetorno.setFont(font)
        self.edtRetorno.setAlignment(QtCore.Qt.AlignCenter)
        self.edtRetorno.setReadOnly(True)
        self.edtRetorno.setObjectName("edtRetorno")
        self.gridLayout.addWidget(self.edtRetorno, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Validar e Gear CPF"))
        self.btnValidarCpf.setText(_translate("MainWindow", "Validar"))
        self.label_2.setText(_translate("MainWindow", "Validar CPF:"))
        self.btnGerarCPF.setText(_translate("MainWindow", "Gerar"))
        self.label.setText(_translate("MainWindow", "Gera CPF"))
